# Generated by Django 5.2.11 on 2026-02-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditscore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
